/* ============================================================
   Build the SELF-CONTAINED demo page served by server.py.
   ------------------------------------------------------------
   examples/agentic_demo/server.py resolves its page from _PAGE_CANDIDATES,
   the FIRST of which is examples/agentic_demo/demo.html (DEMO.md §4 —
   "a self-contained live page the frontend builder may add"). This script
   inlines the modular web/ sources (demo.css + view.js + demo.js) into the
   web/index.html markup and writes that single file to demo.html, so the
   server serves the live page with NO server.py edits and the browser makes
   no extra requests for our own assets.

   web/ stays the canonical source (separately node --check'd + node --test'd);
   demo.html is generated. demo.test.mjs asserts demo.html is in sync (no drift).

   Usage:  node examples/agentic_demo/web/build.mjs
   ============================================================ */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..', '..');            // .../SWITCHBOARD
const OUT = join(HERE, '..', 'demo.html');            // examples/agentic_demo/demo.html

const GENERATED_NOTE =
  '<!-- GENERATED by examples/agentic_demo/web/build.mjs from index.html + demo.css + view.js + demo.js.\n' +
  '     Edit the web/ sources, then re-run the build. Do not hand-edit this file. -->';

/** Produce the self-contained HTML string from the web/ sources. Pure (no I/O
 *  beyond reading sibling source files), so the test can call it directly. */
export function buildHtml() {
  const html = readFileSync(join(HERE, 'index.html'), 'utf8');
  const css = readFileSync(join(HERE, 'demo.css'), 'utf8');
  const view = readFileSync(join(HERE, 'view.js'), 'utf8');
  const demo = readFileSync(join(HERE, 'demo.js'), 'utf8');

  let out = html
    // drop the external stylesheet link; inline the CSS instead
    .replace('<link rel="stylesheet" href="demo.css" />',
      '<style>\n' + css + '\n</style>')
    // inline the two scripts (order preserved: view.js then demo.js)
    .replace('<script src="view.js"></script>',
      '<script>\n' + view + '\n</script>')
    .replace('<script src="demo.js"></script>',
      '<script>\n' + demo + '\n</script>');

  // stamp a generated-file note just after the doctype
  out = out.replace('<!doctype html>', '<!doctype html>\n' + GENERATED_NOTE);
  return out;
}

export const OUT_PATH = OUT;

function isMain() {
  return process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
}

if (isMain()) {
  const out = buildHtml();
  writeFileSync(OUT, out, 'utf8');
  process.stdout.write('[build] wrote ' + OUT + ' (' + out.length + ' bytes)\n');
}
